import pandas as pd
import matplotlib.pyplot as plt

# Read CSV generated by C++ code
data = pd.read_csv("tower_csv.txt")
data = data.sort_values("Disks")

# Extract columns
x = data["Disks"]
y = data["Time_ns"]

# Plot
plt.plot(x, y, marker='o')
plt.xlabel("Number of Disks")
plt.ylabel("Execution Time (ns)")
plt.title("Tower of Hanoi - Exponential Time Complexity")
plt.text(0.5*max(x), 0.8*max(y), "Time Complexity: O(2ⁿ)", fontsize=12)
plt.grid(True)
plt.savefig("towerofhanoi_graph.png")
plt.show()
